### PR TITLE
fix: remove records that exceed size limit in movies.json

### PR DESCRIPTION
**Pull request by AnthYou**
We've deleted the following records that exceed size limit in `movies.json` when uploading to Algolia:
```
    - "objectID": "440221430"
    - "objectID": "440499530"
    - "objectID": "440110110"
```

**Error message:**
Screenshot 2024-12-30 at 15 24 31

### CODE REVIEW

**Review by Haroenv — APPROVED** [review]
Thanks for your PR, this seems like a reasonable solution. Alternatively we could trim those objects down so they fit in the default limit. Would you be interested in contributing that? you could remove some of the alternative titles for example

**Comment by AnthYou** [comment]
> Thanks for your PR, this seems like a reasonable solution. Alternatively we could trim those objects down so they fit in the default limit. Would you be interested in contributing that? you could remove some of the alternative titles for example

I can do it if you prefer to keep them. Both solutions make sense in my opinion!

**Comment by Haroenv** [comment]
Thanks!

**Comment by AnthYou** [comment]
@Haroenv, for the record with the objectID 440499530, the initial size is over 11.57kb, and if we want to fit under the limit of 10kb, we have to remove almost all the alternative titles... I guess it's because of the number of actors involved. Do you still want to go for this solution? Or remove also the actors at the end of the list?

**Comment by Haroenv** [comment]
good point, let's just delete those

**Pull request merged**
